version: '3.4'

services:
  app:
    build:
      context: .
      target: development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: sergiosim/multicons:development
    environment:
      PYLINTHOME: /app/.pylint.d
    volumes:
      - .:/app
