site_name: MultiCons
site_url: https://SergioSim.github.io/multicons
site_description: Multiple Consensuses algorithm implementation
site_author: SergioSim
repo_name: SergioSim/multicons
repo_url: https://github.com/SergioSim/multicons/

theme:
    name: material
    palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
    - smarty

nav:
    - 'Overview': index.md
    - 'API Reference': api.md
    - 'Examples': examples.py
    - 'About the project':
        - 'Changelog': CHANGELOG.md
        - 'License': LICENSE.md

plugins:
    - search
    - mkdocstrings:
        default_handler: python
    - mkdocs-jupyter:
        execute: True
        ignore: ["*.ipynb"]
