version: 2.1

jobs:
  # Check that the git history is clean and complies with our expectations
  lint-git:
    docker:
      - image: circleci/python:3.9-buster
    working_directory: ~/multicons
    steps:
      # Checkout repository sources
      - checkout
      # Make sure the changes don't add a "print" statement to the code base.
      # We should exclude the ".circleci" folder from the search as the very command that checks
      # the absence of "print" is including a "print(" itself.
      - run:
          name: enforce absence of print statements in code
          command: |
            ! git diff origin/master..HEAD -- . ':(exclude).circleci' | grep "print("
      - run:
          name: Check absence of fixup commits
          command: |
            ! git log | grep 'fixup!'
      - run:
          name: Install gitlint
          command: |
            pip install --user gitlint
      - run:
          name: lint commit messages added to master
          command: |
            ~/.local/bin/gitlint --commits origin/master..HEAD

  # Build the package
  build:
    docker:
      - image: cimg/python:3.10.0
    working_directory: ~/multicons
    steps:
      # Checkout repository sources
      - checkout
      - run:
          name: "Build the package"
          command: pip install --user .[dev]
      - save_cache:
          paths:
            - ~/.local
          key: v1-dependencies-{{ .Revision }}

  # Build documentation
  build-docs:
    docker:
      - image: cimg/python:3.10.0
    working_directory: ~/multicons
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Revision }}
      - run:
          name: Build documentation
          command: ~/.local/bin/mkdocs build

  # Deploy documentation to GitHub pages
  deploy-docs:
    docker:
      - image: cimg/python:3.10.0
    working_directory: ~/multicons
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Revision }}
      - add_ssh_keys:
          fingerprints:
            - "ff:ba:34:bf:04:69:af:b9:6f:6b:31:92:7b:49:70:b5"
      - run:
          name: Deploy documentation to GitHub Pages
          command: |
            sudo apt-get update
            sudo apt-get install -y graphviz
            git config --global user.email "katzenmaul@users.noreply.github.com"
            git config --global user.name "Bot"
            ~/.local/bin/mkdocs gh-deploy

  # Lint source code
  lint:
    docker:
      - image: cimg/python:3.10.0
    working_directory: ~/multicons
    steps:
      # Checkout repository sources
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Revision }}
      - run:
          name: Lint code with flake8
          command: ~/.local/bin/flake8
      - run:
          name: Lint code with isort
          command: ~/.local/bin/isort --recursive --check-only .
      - run:
          name: Lint code with black
          command: ~/.local/bin/black src/multicons tests --check
      - run:
          name: Lint code with pylint
          command: ~/.local/bin/pylint src/multicons tests
      - run:
          name: Lint code with bandit
          command: ~/.local/bin/bandit -qr src/multicons

  # Run tests
  test:
    docker:
      - image: cimg/python:3.10.0
    working_directory: ~/multicons
    steps:
      # Checkout repository sources
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Revision }}
      - run:
          name: "Run tests"
          command: ~/.local/bin/pytest

workflows:
  multicons:
    jobs:
      - lint-git:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - build-docs:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      # Publish the documentation website to GitHub Pages.
      - deploy-docs:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /.*/
